version: '3.8'

networks:
  apiGO:

services:
  api:
    build: .
    ports:
    - "8083:8083"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: test_tasksDB
      DB_PORT: 5432
      #keycloak client credentials
      KC_URL: http://172.19.0.1:8180
      KC_CLIENT_ID: todo-app
      KC_CLIENT_SECRET: LSNZqB5JhcqG274tvuOQtHKGMVU5fKPv
      KC_REALM: hermes
    networks:
    - apiGO
    restart: always
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_tasksDB
    networks:
      - apiGO
