version: '3.8'

services:
  test_db:
    image: postgres:latest
    container_name: test_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_tasksDB
    networks:
      apiGO:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tasksDB
    networks:
      - apiGO
  api:
    container_name: api
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: tasksDB
      DB_PORT: 5432
      TEST_DB_HOST: 172.18.0.2
      TEST_DB_NAME: test_tasksDB
    depends_on:
      - db
    networks:
      - apiGO
networks:
  apiGO: 
