version: '3.8'

services:
  test_db:
    image: postgres:latest
    container_name: test_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test_tasksDB
    networks:
      apiGO:
       ipv4_address: 172.19.0.2
networks:
  apiGO:
    ipam:
      config:
        - subnet: 172.19.0.0/16
