name: api build

on: 
  push:
    branches: [ main ]

jobs:
  build-pust-grc:
    name: Build api
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: api-tasks
      PROJECT_ID: taskapi-415921
      GIT_TAG: steps.increment-git-tag.outputs.git-tag

  
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.7 

    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
        version: '333.0.0'

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:$GIT_TAG .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        
        docker tag $IMAGE_NAME:$GIT_TAG us-central1-docker.pkg.dev/$PROJECT_ID/api-rep/$IMAGE_NAME:$GIT_TAG
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/api-rep/$IMAGE_NAME:$GIT_TAG