name: api build

on: 
  push:
    branches: [ main ]

jobs:
  build-pust-grc:
    name: Build api
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: api-tasks
      PROJECT_ID: taskapi-415921
      DB_HOST: "10.0.1.3"
      DB_USER: "postgres"
      DB_PASSWORD: "1234"
      DB_NAME: "task_apiDB"
      DB_PORT: "5432"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{secrets.SERVICE_ACCOUNT_KEY}}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      run: |-
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push us-central1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG